"""
pod_registry.py

Defines the pod farm layout: every pod's physical position on the
rail/gantry structure, which crop it holds, and which "ground truth"
image stands in for that pod's live camera frame.

Design note (documented substitution, see handoff doc Section 6):
Physical pods/plants don't exist, so at each stop the simulated robot
loads a real dataset image pre-matched to a known ground-truth
condition instead of rendering organic matter. In this standalone
build (Step 4) that image pool is a small set of placeholder images
generated by generate_placeholder_images.py; swap PODS[i]["image_path"]
to point at real Roboflow/Mendeley crops once they're wired in — no
other code needs to change, since the rest of the pipeline only cares
about the path.

Layout convention:
  - LAYERS vertical layers on the rail (Z axis, meters)
  - POSITIONS_PER_LAYER lateral pod slots per layer (X axis, meters)
  - Y is fixed (depth into the pod shelf) since the gantry doesn't move in Y
"""

import itertools
import os

CROPS = ["cabbage", "lettuce", "mushroom"]

# Growth stages per crop (must match the fixed Roboflow class lists)
GROWTH_STAGES = {
    "cabbage": ["S2_3", "S4_5", "S6_7", "S8", "S9"],
    "lettuce": ["Early Growth", "Leafy growth", "Head formation", "Harvest stage"],
    "mushroom": ["Juvenile", "Intermediate", "Harvest"],
}

LAYERS = 3               # vertical layers
POSITIONS_PER_LAYER = 4  # lateral pod slots per layer

LAYER_SPACING_M = 0.55        # vertical gap between layers
POSITION_SPACING_M = 0.45     # lateral gap between pod slots
BASE_HEIGHT_M = 0.30          # height of the lowest layer off the ground
SHELF_DEPTH_M = 0.35          # fixed Y offset where pods sit relative to the rail

IMAGE_DIR = os.path.join(os.path.dirname(__file__), "sample_images")


def _ground_truth_cycle():
    """
    Deterministic, repeatable assignment of (growth_stage, disease) ground
    truth to pods, so a demo run is reproducible and includes a mix of
    healthy/diseased and early/late growth stages -- useful for showing
    the decision agent actually branching, not just logging one outcome
    over and over.
    """
    pattern = [
        # (stage_index_from_end, diseased)
        (0, False),   # earliest stage, healthy
        (1, False),
        (2, True),    # mid stage, diseased -> should trigger "flag for treatment"
        (-1, False),  # last (harvest) stage, healthy -> should trigger "log & move on" / harvest note
    ]
    return itertools.cycle(pattern)


def build_pod_registry():
    """Returns a list of pod dicts describing the full farm layout."""
    pods = []
    crop_cycle = itertools.cycle(CROPS)
    pod_index = 0

    for layer in range(LAYERS):
        gt_cycle = _ground_truth_cycle()
        for slot in range(POSITIONS_PER_LAYER):
            crop = next(crop_cycle)
            stages = GROWTH_STAGES[crop]
            stage_offset, diseased = next(gt_cycle)
            stage = stages[stage_offset if stage_offset >= 0 else len(stages) - 1]

            pod_id = f"L{layer}-P{slot}"
            image_name = f"{crop}_{stage}_{'diseased' if diseased else 'healthy'}.png".replace(" ", "_")

            pods.append({
                "pod_id": pod_id,
                "index": pod_index,
                "layer": layer,
                "slot": slot,
                "crop_type": crop,
                "position_m": {
                    "x": slot * POSITION_SPACING_M,
                    "y": SHELF_DEPTH_M,
                    "z": BASE_HEIGHT_M + layer * LAYER_SPACING_M,
                },
                "ground_truth": {
                    "growth_stage": stage,
                    "diseased": diseased,
                },
                "image_path": os.path.join(IMAGE_DIR, image_name),
            })
            pod_index += 1

    return pods


PODS = build_pod_registry()


def get_pod(pod_id):
    for p in PODS:
        if p["pod_id"] == pod_id:
            return p
    raise KeyError(f"Unknown pod_id: {pod_id}")


def pod_visit_order():
    """
    Serpentine (boustrophedon) traversal: sweep each layer left-to-right,
    then right-to-left on the next, minimizing lateral travel between
    consecutive stops rather than resetting to slot 0 every layer.
    """
    order = []
    for layer in range(LAYERS):
        layer_pods = [p for p in PODS if p["layer"] == layer]
        layer_pods.sort(key=lambda p: p["slot"])
        if layer % 2 == 1:
            layer_pods.reverse()
        order.extend(layer_pods)
    return order


if __name__ == "__main__":
    for p in pod_visit_order():
        print(p["pod_id"], p["crop_type"], p["ground_truth"], p["position_m"])
